// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package signup.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the SignUp module
	public static void aCT_Submit_SignUp(IContext context, signup.proxies.SignUpForm _signUpForm)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SignUpForm", _signUpForm == null ? null : _signUpForm.getMendixObject());
		Core.microflowCall("SignUp.ACT_Submit_SignUp").withParams(params).execute(context);
	}
	public static void nAV_SignUp(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("SignUp.NAV_SignUp").withParams(params).execute(context);
	}
}